### PR TITLE
Support Basic Auth

### PR DESCRIPTION
**Pull request by arjunkomath**
## Changes

- Move form validation to view model
- Add support for basic auth
- Add indicator for basic auth

**TODO: Show valid errors**

## Screenshot
IMG_566B7B9C1A7E-1

### CODE REVIEW

**Comment by arjunkomath** [comment]
@kobimx Please review this PR if time permits.

**Comment by kobimx** [comment]
will do as soon as i can ✌️

anything specific i should look for?

**Comment by arjunkomath** [comment]
> will do as soon as i can ✌️
> 
> anything specific i should look for?

- I'm not super happy with `NetDataAPI.swift`, Is there a cleaner way of passing base64 encoded header string?
- Also should we show a message stating that the base64 string will be saved to iCloud as its a matter of privacy / security?

**Comment by kobimx** [comment]
> I'm not super happy with NetDataAPI.swift, Is there a cleaner way of passing base64 encoded header string?

Do you mean this `basicAuthBase64: String = ""`? having to pass an empty string and then check if it is empty? if so you can just as easily use optional value types (setting this `basicAuthBase64: String?` and unwrapping the value)
if that's not the case then i'm dumb

> Also should we show a message stating that the base64 string will be saved to iCloud as its a matter of privacy / security?

Well, i don't know :/ here in Europe we have the GDPR laws but they regard personal info not generic data like passwords
Maybe a little disclaimer isn't a bad idea

Also just out of curiosity i was wondering, why did you reverted back to using the old toolbars method? Did it break something? Asking because now the UI text glitches are back :S

**Comment by arjunkomath** [comment]
- `basicAuthBase64` string was being passed around a lot, was wondering if there was a way to cleanup that.
- I'll add the disclaimer that the base 64 is stored in iCloud.
- Sorry about the toolbar change, I'll revert it. I was testing something and forgot to revert it.

**Comment by kobimx** [comment]
Oh i see; well it seems to be working correctly so you should be all set, to make a change like that i think that the whole code should be completely rewritten
(For that matter even `requestUrl` gets passed around a lot, but again it works as is so👌)

**Pull request merged**
